/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaproject3;

import java.util.LinkedList;
import java.util.List;
import java.util.Scanner;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

public class BankAccountApp {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new BankAccountApp().getGreeting());

        List<Account> Accounts = new LinkedList<Account>();

        System.out.println("Input name of CSV file: ");
        
        Scanner in = new Scanner(System.in);

        String file = in.nextLine();

        //Create accounts based on data from the CSV file
        List<String[]> newAccountHolders = utilities.CSV.read(file);
        for(String[] newAccountHolder : newAccountHolders){
            String name = newAccountHolder[0];
            String ssn = newAccountHolder[1];
            String accountType = newAccountHolder[2];
            double initDeposit = Double.parseDouble(newAccountHolder[3]);
            
            if(accountType.equals("Savings")){
                Accounts.add(new Savings(name,ssn,initDeposit));
            } else if(accountType.equals("Checking")){
                Accounts.add(new Checking(name,ssn,initDeposit));
            } else{
                System.out.print("Failed to read account type");
            }
        }

        Accounts.get(5).showInfo();

        for(Account acc: Accounts){
            System.out.println("\n****************\n");
            acc.showInfo();
        }

    }

}
